# Generated by Django 4.2.28 on 2026-03-12 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_post_image_post_post_type_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('gold', '🥇 Gold'), ('silver', '🥈 Silver'), ('bronze', '🥉 Bronze'), ('funny', '😂 Funny'), ('helpful', '🙏 Helpful'), ('hot', '🔥 Hot')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='posts.comment')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_awards', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='posts.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('giver', 'award_type', 'post'), name='unique_post_award'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('giver', 'award_type', 'comment'), name='unique_comment_award'),
        ),
    ]
