# Generated by Django 4.2.28 on 2026-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_award_award_unique_post_award_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='award',
            name='unique_post_award',
        ),
        migrations.RemoveConstraint(
            model_name='award',
            name='unique_comment_award',
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('giver', 'post'), name='unique_post_award'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('giver', 'comment'), name='unique_comment_award'),
        ),
    ]
