# Generated by Django 4.2.28 on 2026-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification_actor_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reply', 'Reply'), ('award', 'Award'), ('follow', 'Follow')], default='reply', max_length=20),
        ),
    ]
